### ISSUE TITLE
Prehodnotiť dodatočné požiadavky

### ISSUE THREAD

**Issue by Nightwalker495** [Nightwalker495/RegisterOfficeIS#2]
Prehodnotiť požiadavky od druhého tímu - do akej miery sme schopný im vyhovieť s aktuálnym modelom.

**Comment by n0rdh** [comment]
1.) aktualny model postacuje, bez dalsich uprav
2.) prediskutovat navrh o zavedeni ID manzelstva. Riesenie je mozne s aktualnym modelom
3.) postacuje, otazka znie. Bezdetny? ako konkretne overit tuto podmienku
4.) postacuje
5.) model postacuje, problem je v otazke. Do akej hlbky budeme riesit pribuznych? pribuzny
     viacerymi smermi? starsi (rodicia,stary rodicia,..) mladsi (deti, neter, vnuca,..) 
     rovnaka generacia(surodenci,bratranci,..). Pokrvny, pripadne po svadbe?
ID manzelstva: (1,1,00,1,C) (muz,zena,pocet_deti_pred_uzavretim,platny,typ) len maly navrh, tie 
deti by bolo pekne vyriesit krajsie. Asi treba rozlisit deti muza a zaroven deti zeny pred uzavretim. viac miestne cislo to kazi.

**Comment by Nightwalker495** [comment]
Požiadavky odoslané a druhým tímom prijaté. Uzatváram.
