### ISSUE TITLE
Zber informácií o PSČ, úmrtia atď.

### ISSUE THREAD

**Issue by Nightwalker495** [Nightwalker495/RegisterOfficeIS#4]
Získať informácie ohľadom možných príčin smrti, ako fungujú PSČ miest a navrhnúť čo najlepšie využitie, keďže môžu byť otázky s cieľom robiť výstupy pre kraj, okres a podobne.

**Comment by n0rdh** [comment]
Podľa ust. § 16 zák. č. 154/1994 Z.z. o matrikách ženské priezvisko osoby inej ako slovenskej národnosti sa zapíše bez koncovky slovenského prechyľovania ("ova", prechylovanie)

Pri narodeni dietata v pripade ze maju rodicia rozdielne narodnosti (slovenska : ina), dieta ziska obe narodnosti, ak jeden z rodicou je v cudzej krajine dlhsie ako n rokov(n podla krajiny,vacsinou 5)a plati dane, alebo je inej narodnosti. Takato situacia sa riesi v specialnej matrike. Zahrnieme? 

Asi je potrebne riesit aj spominanu narodnost

**Comment by Nightwalker495** [comment]
Katka obstarala celý zoznam s PSČ a podobnými informáciami, úmrtia budeme kategorizovať do nejakých 5 hlavných skupín.
